config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  resources :users, only: [:show]

  resources :events do
    resources :tickets, only: [:create]
  end

  resources :profiles, only: [:new, :edit, :create, :update]

  resources :photos

  get "about" => "pages#about"

  namespace :api do
    resources :events, except: [:edit, :new] do
      resources :tickets, only: [:create, :update, :destroy]
    end
    resources :themes, except: [:edit, :new]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_and_belongs_to_many :themes
  has_many :tickets, dependent: :destroy
  has_many :attendants, through: :tickets, source: :user

  validates :name, :location, :starts_at,
    presence: true
  # validates :ends_at,
  #   date: { after_or_equal_to:  :starts_at}
  validates :description,
    length: { maximum: 500 }

  scope :published, -> { where(active: true) }

  def self.alphabetical
    order(name: :asc)
  end

  def bargain?
    price <= 30
  end

  def self.order_by_price
    order price: :asc
  end

  # t.string :name
  # t.text :description
  # t.string :location
  # t.decimal :price
  # t.integer :capacity
  # t.boolean :includes_food
  # t.boolean :includes_drinks
  # t.datetime :starts_at
  # t.datetime :ends_at
  # t.boolean :active
  # t.references :user, foreign_key: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader

end

app/models/profile.rb
class Profile < ApplicationRecord
#  belongs_to :user THIS IS NOT NECESSARY BUT ADDED BY DEF

  validates :first_name, :last_name, :user_id,
    presence: true

  def full_name
    first_name + " " + last_name
  end
end

app/models/theme.rb
class Theme < ApplicationRecord
  
  has_and_belongs_to_many :events

  validates :name, presence: true, uniqueness: true

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :event

  before_save :set_total_price

  def self.startsbefore_endsafter(arrival, departure)
    where('starts_at < ? AND ends_at > ?', arrival, departure)
  end

  def self.starts_during(arrival, departure)
    where('starts_at > ? AND starts_at < ?', arrival, departure)
  end

  def self.ends_during(arrival, departure)
    where('ends_at > ? AND ends_at < ?', arrival, departure)
  end

  def self.during(arrival, departure)
      arrival = arrival.change(hour: 14, min: 00, sec: 00)
      departure = departure.change(hour: 11, min: 00, sec: 00)

      startsbefore_endsafter(arrival, departure)
      .or(starts_during(arrival, departure))
      .or(ends_during(arrival, departure))
  end

  def self.sametime_events(arrival, departure)
    during(arrival, departure).pluck(:event_id)
  end

  def self.non_sametime_events(arrival, departure)

  end

  def set_total_price
    self.price = event.price * amount
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_token

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :tickets, dependent: :destroy
  has_many :attended_events, through: :tickets, source: :event

  def has_profile?
    profile.present? && profile.persisted?
  end

  def full_name
    profile.full_name
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
    #  @events = Event.all # shows all the events
  end

  def show
    @themes = @event.themes
    @photos = @event.photos
  end

  def new
    @event = current_user.events.build


  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      image_params.each do |i|
        @event.photos.create(image: i)
      end

      redirect_to edit_event_path(@event), notice: "Event created!"
    else
      render :new
    end
  end

  def edit
    if current_user.id == @event.user.id
      @photos = @event.photos
    else
      redirect_to events_path, notice: "You smart! But you still do not have permission."
    end
  end

  def update
    if @event.update(event_params)
      image_params.each do |i|
        @event.photos.create(image: i)
      end

      redirect_to edit_event_path(@event), notice: "Event updated"
    else
      render :edit
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def image_params
    params[:images].present? ? params.require(:images) : []
  end

  def event_params
    params
      .require(:event)
      .permit(
        :name, :description, :location, :starts_at, :ends_at, :active,
        :price, :capacity, :includes_food, :includes_drinks, theme_ids: []
      )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about; end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

def destroy
  photo = Photo.find(params[:id])
  @event = photo.event
  if current_user.id == @event.user.id
    photo.destroy
    redirect_to edit_event_path(@event), notice: "Photo removed."
  else
    redirect_to events_path, notice: "You smart! But you still do not have permission."
  end

end

end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodaisseurUP</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "shared/navbar" %>

    <div class="container">

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="sidebar" class="col-xs-6 col-md-4">
      <p>This is a sidebar</p>
    </div>
    <div id="content" class="col-xs-12 col-md-8">
      <h1>About page</h1>

      <p>This application was built in 2017.</p>
    </div>
  </div>
</div>
<div class="container">
  <div class="col-md-4">
    <p>I am column 1</p>
  </div>
  <div class="col-md-4">
    <p>I am column 2</p>
  </div>
  <div class="col-md-4">
    <p>I am column 3</p>
  </div>
</div>

app/views/pages/home.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="sidebar" class="col-xs-6 col-md-4">
      <p>This is a sidebar</p>
    </div>
    <div id="content" class="col-xs-12 col-md-8">
      <h1>Homepage</h1>

      <p>Main content</p>
    </div>
  </div>
</div>
<div class="container">
  <div class="col-md-4">
    <p>I am column 1</p>
  </div>
  <div class="col-md-4">
    <p>I am column 2</p>
  </div>
  <div class="col-md-4">
    <p>I am column 3</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "CodaisseurUP", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_user.has_profile? ? current_user.full_name : current_user.email  %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to "Your Events", events_path %></li>
              <li role="separator" class="divider"></li>
              <% if current_user.has_profile? %>
                <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
              <% else %>
                <li><%= link_to "Create Profile", new_profile_path %></li>
              <% end %>
              <li><%= link_to "Edit Password", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_validation_errors.html.erb
<!-- <% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: "alert alert-#{name}" %>
<% end -%> -->